### ISSUE TITLE
OSX build fails

### ISSUE THREAD

**Issue by stuta** [pocomane/luachild#2]
Maybe you should put these calls in luachild.h as static int.

```bash 
luarocks make

env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/opt/lua/include/lua5.3 -c luachild_common.c -o luachild_common.o -DUSE_POSIX -I./
In file included from luachild_common.c:10:
./luachild.h:32:12: warning: function 'process_tostring' has internal linkage but is not defined [-Wundefined-internal]
static int process_tostring(lua_State *L);
           ^
luachild_common.c:26:24: note: used here
  lua_pushcfunction(L, process_tostring);
...
```

**Comment by pocomane** [comment]
Thanks for the report!

I hope that the last commit (74fa5a4c4901291fb493296a6c95da01e217d8a1) will fix this issue. I have no OSX machine to test it.

**Comment by stuta** [comment]
Now luarocks make works. When I'm trying to use it with Luajit in https://github.com/softdevteam/lua_benchmarking then I get this error:

```bash
error loading module 'luachild' from file './luachild.so':
	dlopen(./luachild.so, 6): Symbol not found: _lua_rawlen
```

**Comment by pocomane** [comment]
You may have a VM mismatch issues since luachild_lua uses lua_rawlen while luachild_luajit never calls it. Maybe you are using a .so compiled for PUC-lua instead of luajit?

However, how do you complie luachild for luajit? The provided rockspec compiles only versus PUC lua. I will try in the next days to handle luajit in the rockspec. For now you have to manually call gcc.

I will close this issue. If you need, please open another issue about luajit.
